# Site
name: 'PhiVAR'
description: 'Información que te importa'
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
baseurl: '/phivar'
disqus: 'demowebsite
email: 'contacto@consultancysoft.com'
mailchimp-list: ''

include: ["_pages"]
permalink: /:title/

# Plugins
plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  
authors:
    fierro:
      name:           Francisco Fierro
      site:           https://www.meowsoft.net
      avatar:         /assets/images/avatar1.jpg
      bio:            "Soy Francisco, estudiante de Ingeniería Informática, desde siempre me ha gustado la informática, el desarrollo de software, la electrónica, la tecnología, la administración de sistemas y un largo etc. Por otra parte, me desenvuelvo como audiovisualita en mis tiempos libres y practico composición fotográfica. Actualmente trabajo como Soporte Técnico y tengo mis propios proyectos de desarrollo de software."
      email:          fjff603@gmail.com
      twitter:        https://twitter.com/FrancisIr0n

    mako:
      name:           Macarena Millapán
      site:           https://consultancysoft.com
      avatar:         /assets/images/avatar2.jpg
      bio:            "Soy Macarena, Ingeniero civil Industrial de profesión, pero me encanta lo relacionado al mundo digital, se programar en distintos lenguajes y ahora estoy incursionando en lo que es desarrollo web, se hacer páginas web tanto estáticas como dinámicas, se de gestión de proyectos uso la metodología de PMI, también soy fotógrafa en mis tiempos libres. Se ampliamente lo relacionado con marketing, y marketing digital también. Escribo mi propio blog."
      email:          macarena.millapan.c@gmail.com
      twitter:        https://twitter.com/MeiSerene
 
# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      
  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page
      
# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 10



# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]
